[[telescopes]]
name = "fake1"
enabled = true
location = [ 0.20802143022, 1.00170457462 ]
min_elevation = 0.087
telescope_type = "Fake"

[[telescopes]]
name = "fake2"
enabled = true
location = [ 0.20802143022, 1.00170457462 ]
min_elevation = 0.087
telescope_type = "Fake"

[[telescopes]]
name = "fakesalsa"
enabled = true
location = [ 0.20802143022, 1.00170457462 ]
min_elevation = 0.087
telescope_type = "Salsa"
controller_address = "127.0.0.1:3001"
receiver_address = "127.0.0.1:3002"

[[telescopes]]
name = "brage"
enabled = false
location = [ 0.20802143022, 1.00170457462 ]
min_elevation = 0.087
telescope_type = "Salsa"
controller_address = "192.168.5.10:23"
receiver_address = "192.168.5.30"

[[telescopes]]
name = "vale"
enabled = false
location = [ 0.20802143022, 1.00170457462 ]
min_elevation = 0.087
telescope_type = "Salsa"
controller_address = "192.168.5.11:23"
receiver_address = "192.168.5.31"

[[telescopes]]
name = "torre"
enabled = false
location = [ 0.20802143022, 1.00170457462 ]
min_elevation = 0.087
telescope_type = "Salsa"
controller_address = "192.168.5.12:23"
receiver_address = "192.168.5.32"
