[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.24.2", features = ["macros", "rt-multi-thread"] }
warp = { version = "0.3.3" }
serde = {version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
common = { version = "0.1.0", path = "../common" }
rand = "0.8.5"